# Generated by Django 5.2.6 on 2025-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("original_url", models.URLField(unique=True)),
                (
                    "short_code",
                    models.CharField(
                        help_text="Unique code for the shortened URL",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shortened URL",
                "verbose_name_plural": "Shortened URLs",
                "ordering": ["-created_date"],
            },
        ),
    ]
